#!/usr/bin/env python3
"""[DET-SOLID-001][C4] Convert a Firestore diagnostics session export into a Kotlin replay fixture.

Input: a JSON array of the session's `events` documents (as returned by the Firestore MCP
`firestore_list_documents` on `diagnostics/{uid}/sessions/{sessionId}/events`, or an equivalent
export) — only LOCATION_FIX and STEP events are consumed.

Usage:
    python trace2fixture.py events.json TRACE_MY_BUG > Trace_MyBug.kt

Then move the file to composeApp/src/commonTest/kotlin/io/apptolast/paparcar/domain/coordinator/replay/
and write a DetectionTraceReplayTest case asserting the corrected outcome.
"""
import json
import sys


def field(doc: dict, name: str):
    """Supports both raw Firestore REST docs ({fields:{x:{doubleValue:..}}}) and flat dicts."""
    if "fields" in doc:
        value = doc["fields"].get(name)
        if value is None:
            return None
        return next(iter(value.values()))
    return doc.get(name)


def main() -> None:
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    events = json.load(open(sys.argv[1], encoding="utf-8"))
    if isinstance(events, dict):
        events = events.get("documents", [])
    name = sys.argv[2]

    rows = []
    for doc in events:
        kind = field(doc, "type")
        t = int(field(doc, "timestampMs") or 0)
        if kind == "LOCATION_FIX":
            rows.append((t, "FIX", float(field(doc, "lat") or 0), float(field(doc, "lon") or 0),
                         float(field(doc, "accuracy") or 0), float(field(doc, "speed") or 0)))
        elif kind == "STEP":
            rows.append((t, "STEP", 0, 0, 0, 0))
        elif kind == "ACTIVITY_TRANSITION":
            # [DET-MOTORWAY-TRIP-JUDGED-BICYCLE-001] The AR lane rides in the fixture too: the
            # vehicle-exit is what routes the scorer into its Medium-capped fast path, and the
            # cycling stamp is what can veto a whole session — a replay that drops either cannot
            # reproduce what the session actually did. Both are replayed at their TRUE transition
            # time (delivery time minus the recorded staleness), because that is the clock the
            # human-powered verdict arbitrates on.
            activity, transition = field(doc, "activity"), field(doc, "transition")
            true_t = t - int(field(doc, "enterAgeMs") or 0)
            if activity == "IN_VEHICLE" and transition == "EXIT":
                rows.append((t, "VEHICLE_EXIT", 0, 0, 0, 0))
            elif activity == "ON_BICYCLE" and transition == "ENTER":
                rows.append((true_t, "BICYCLE_ENTER", 0, 0, 0, 0))
    rows.sort(key=lambda r: r[0])
    if not rows:
        sys.exit("no LOCATION_FIX/STEP events found")

    t0 = rows[0][0]
    print("package io.apptolast.paparcar.domain.coordinator.replay\n")
    print(f"/** Generated by tools/trace2fixture from a diagnostics session export (t0={t0}). */")
    print(f"val {name}: List<TraceEvent> = buildList {{")
    print(f"    val t0 = {t0}L")
    print("    fun fix(dtMs: Long, lat: Double, lon: Double, acc: Float, speed: Float) =")
    print("        add(TraceEvent(t0 + dtMs, TraceEvent.Kind.FIX, lat, lon, acc, speed))")
    print("    fun step(dtMs: Long) = add(TraceEvent(t0 + dtMs, TraceEvent.Kind.STEP))")
    print("    fun vehicleExit(dtMs: Long) = add(TraceEvent(t0 + dtMs, TraceEvent.Kind.VEHICLE_EXIT))")
    print("    fun bicycleEnter(dtMs: Long) = add(TraceEvent(t0 + dtMs, TraceEvent.Kind.BICYCLE_ENTER))")
    for t, kind, lat, lon, acc, speed in rows:
        dt = t - t0
        if kind == "FIX":
            print(f"    fix({dt}, {lat}, {lon}, {acc}f, {speed}f)")
        elif kind == "VEHICLE_EXIT":
            print(f"    vehicleExit({dt})")
        elif kind == "BICYCLE_ENTER":
            print(f"    bicycleEnter({dt})")
        else:
            print(f"    step({dt})")
    print("}")


if __name__ == "__main__":
    main()
